# Generated by Django 5.0.1 on 2024-04-19 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0014_remove_room_shelf_hall_shelf"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hall",
            name="shelf",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.shelf",
                verbose_name="Prateleira",
            ),
        ),
    ]
