# Generated by Django 5.0.1 on 2024-05-01 00:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0017_productunit_meters_productunit_ncm"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome da Cor")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cor",
                "verbose_name_plural": "Cores",
            },
        ),
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da Estampa"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estampa",
                "verbose_name_plural": "Estampas",
            },
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"verbose_name": "Loja", "verbose_name_plural": "Lojas"},
        ),
        migrations.AddField(
            model_name="productunit",
            name="code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Código"
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.color",
                verbose_name="Cor",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pattern",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.pattern",
                verbose_name="Estampa",
            ),
        ),
    ]
