# Generated by Django 5.0.1 on 2024-05-01 00:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0018_color_pattern_alter_building_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productunit",
            options={
                "ordering": ["purchase_date", "product"],
                "verbose_name": "Unidade de Produto",
                "verbose_name_plural": "Unidades de Produto",
            },
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="write_off",
        ),
        migrations.CreateModel(
            name="StockReposition",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Metros"
                    ),
                ),
                (
                    "observations",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                ("reposition_date", models.DateField(verbose_name="Data da Reposição")),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory_management.productunit",
                        verbose_name="Unidade de Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reposição de Estoque",
                "verbose_name_plural": "Reposições de Estoque",
            },
        ),
        migrations.CreateModel(
            name="StockWriteOff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "meters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Metros"
                    ),
                ),
                ("write_off_date", models.DateField(verbose_name="Data da Baixa")),
                (
                    "observations",
                    models.TextField(blank=True, null=True, verbose_name="Observações"),
                ),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory_management.productunit",
                        verbose_name="Unidade de Produto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Baixa de Estoque",
                "verbose_name_plural": "Baixas de Estoque",
            },
        ),
    ]
