# Generated by Django 5.0.1 on 2024-04-29 22:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0019_productunit_code"),
    ]

    operations = [
        migrations.CreateModel(
            name="Color",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nome da Cor")),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cor",
                "verbose_name_plural": "Cores",
            },
        ),
        migrations.CreateModel(
            name="Pattern",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nome da Estampa"),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        editable=False,
                        max_length=100,
                        null=True,
                        verbose_name="Slug",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estampa",
                "verbose_name_plural": "Estampas",
            },
        ),
        migrations.AlterModelOptions(
            name="building",
            options={"verbose_name": "Loja", "verbose_name_plural": "Lojas"},
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="color",
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="pattern",
        ),
        migrations.RemoveField(
            model_name="productunit",
            name="type",
        ),
    ]
