# Generated by Django 5.0.1 on 2024-04-29 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory_management", "0020_color_pattern_alter_building_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.color",
                verbose_name="Cor",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="pattern",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory_management.pattern",
                verbose_name="Estampa",
            ),
        ),
    ]
