# Generated by Django 5.0.1 on 2025-03-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0084_remove_productunit_metro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='code',
        ),
        migrations.AddField(
            model_name='product',
            name='code1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='code2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Código 2'),
        ),
    ]
