# Generated by Django 5.0.1 on 2025-03-17 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0085_remove_productunit_code_product_code1_product_code2'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='code',
            field=models.CharField(default='prd', editable=False, max_length=10, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
