# Generated by Django 5.0.1 on 2025-03-17 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0085_product_code1_product_code2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='code',
        ),
    ]
