# Generated by Django 5.0.1 on 2025-07-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0086_alter_workspace_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storagetype',
            name='is_deposito',
            field=models.BooleanField(default=False, verbose_name='É Depósito?'),
        ),
    ]
