# Generated by Django 5.0.1 on 2025-07-09 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0086_alter_workspace_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='is_divided',
            field=models.BooleanField(default=False, verbose_name='Unidade Dividida?'),
        ),
    ]
