# Generated by Django 5.0.1 on 2025-03-17 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0086_remove_productunit_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='code',
            field=models.CharField(editable=False, max_length=10, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
    ]
