# Generated by Django 5.0.1 on 2025-07-09 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0087_productunit_is_divided'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='source_unit',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='source_units', to='inventory_management.productunit', verbose_name='Unidade Fonte'),
        ),
    ]
