# Generated by Django 5.0.1 on 2025-07-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0088_productunit_source_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workspace',
            options={'permissions': [('can_view_workspace_write_off', 'Can view workspace write off'), ('can_view_workspace_divide', 'Can view workspace divide')], 'verbose_name': 'Área de Trabalho', 'verbose_name_plural': 'Áreas de Trabalho'},
        ),
    ]
