# Generated by Django 5.0.1 on 2026-07-15 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_management', '0089_alter_workspace_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productunit',
            options={'ordering': ['write_off', 'purchase_date', 'product'], 'permissions': [('can_generate_qr_code', 'Can generate QR code')], 'verbose_name': 'Unidade de Produto', 'verbose_name_plural': 'Unidades de Produto'},
        ),
    ]
